**Вариант 10**

**Практическая работа 1**

Исходные данные

In [8]:
import pandas as pd
import numpy as np

data = {
    'ID': range(1, 11),
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva',
             'Frank', 'Grace', 'Helen', 'Ivan', 'Julia'],
    'Age': [23, 35, 29, 40, 28, 45, 32, 27, 38, 31],
    'City': ['Moscow', 'SPb', 'Moscow', 'Kazan', 'SPb',
             'Moscow', 'SPb', 'Kazan', 'Moscow', 'SPb'],
    'Salary': [50000, 70000, 60000, 80000, 55000,
               90000, 65000, 58000, 75000, 62000]
}

df = pd.DataFrame(data)
print(df)

   ID     Name  Age    City  Salary
0   1    Alice   23  Moscow   50000
1   2      Bob   35     SPb   70000
2   3  Charlie   29  Moscow   60000
3   4    David   40   Kazan   80000
4   5      Eva   28     SPb   55000
5   6    Frank   45  Moscow   90000
6   7    Grace   32     SPb   65000
7   8    Helen   27   Kazan   58000
8   9     Ivan   38  Moscow   75000
9  10    Julia   31     SPb   62000

**1. Вывести последние 5 строк с помощью .tail()**

In [9]:
df.tail()

   ID   Name  Age    City  Salary
5   6  Frank   45  Moscow   90000
6   7  Grace   32     SPb   65000
7   8  Helen   27   Kazan   58000
8   9   Ivan   38  Moscow   75000
9  10  Julia   31     SPb   62000

 **2. Выбрать строки с нечетными индексами (1, 3, 5, ...)**

In [10]:
df.iloc[1::2]

   ID   Name  Age    City  Salary
1   2    Bob   35     SPb   70000
3   4  David   40   Kazan   80000
5   6  Frank   45  Moscow   90000
7   8  Helen   27   Kazan   58000
9  10  Julia   31     SPb   62000

**3. Выбрать строки, где Age кратен 5 (используйте Age % 5 == 0)**

In [11]:
df[df['Age'] % 5 == 0]

   ID   Name  Age    City  Salary
1   2    Bob   35     SPb   70000
3   4  David   40   Kazan   80000
5   6  Frank   45  Moscow   90000

**4. Найти 3 самые высокие зарплаты ( .nlargest(3, 'Salary') )**

In [12]:
df.nlargest(3, 'Salary')

   ID   Name  Age    City  Salary
5   6  Frank   45  Moscow   90000
3   4  David   40   Kazan   80000
8   9   Ivan   38  Moscow   75000

**5. Создать столбец Tax = 13% от Salary**

In [13]:
df['Tax'] = df['Salary'] * 0.13
df

   ID     Name  Age    City  Salary      Tax
0   1    Alice   23  Moscow   50000   6500.0
1   2      Bob   35     SPb   70000   9100.0
2   3  Charlie   29  Moscow   60000   7800.0
3   4    David   40   Kazan   80000  10400.0
4   5      Eva   28     SPb   55000   7150.0
5   6    Frank   45  Moscow   90000  11700.0
6   7    Grace   32     SPb   65000   8450.0
7   8    Helen   27   Kazan   58000   7540.0
8   9     Ivan   38  Moscow   75000   9750.0
9  10    Julia   31     SPb   62000   8060.0